MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  commands:
    levels:
      command: rankup
      aliases: [rank, ranks, level, levels, nivel, niveis]
    clothes:
      command: clothes
      aliases: [roupa, roupas, armadura, armaduras]
  admin-permission: ranks.admin
  data-update-interval: 600 # segundos
  rank-permission: rank.{level} # permissão que será adicionada ao jogador
  add-lower-ranks-permission: true # adicionar as permissões dos ranks anteriores
  clothes-pickup-cooldown: 5 # segundos
  default-level: 1
  max-level: 500
  progress-digits: 2
  clothes-digits: 4
  thunder: # raio quando o jogador evoluir de nível
    enabled: true
    double: true # double thunder = efeito sonoro extra
    silent: false

#
# Placeholders disponíveis:
#
# {level} - Nível do jogador (tag)
# {player} - Nick do jogador (comandos | mensagens | action-bar)
# {old_level} - Nível antigo (comandos | mensagens | action-bar)
# {new_level} - Novo nível (comandos | mensagens | action-bar)
# {old_level_tag} - Tag do nível antigo (comandos | mensagens | action-bar)
# {new_level_tag} - Tag do novo nível (comandos | mensagens | action-bar)
#
Levels:
    1-20:
      tag: '&7[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 3'
      action-bar: '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
    21-50:
      tag: '&a[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 4'
      action-bar: '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
    51-100:
      tag: '&b[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 5'
      action-bar: '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
    101-200:
      tag: '&5[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 6'
      messages:
        - ''
        - '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
        - ''
    201-300:
      tag: '&c[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 7'
      messages:
        - ''
        - '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
        - ''
    301-400:
      tag: '&4[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 8'
      messages:
        - ''
        - '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
        - ''
    401-500:
      tag: '&6[Lv. {level}]'
      commands:
        - 'crates give {player} Rankup 10'
      messages:
        - ''
        - '&7O jogador &f{player} &7evoluiu para o {new_level_tag}&7!'
        - ''

Messages:
  new-level:
    - ''
    - ' &eSua armadura acaba de ser evoluída!'
    - ' &7&mNível {old_level}&8 ➟ &7Nível {new_level} &8(Novo bônus de {new_bonus}x)'
    - ''
  new-clothes:
    - ''
    - ' &eUm novo visual foi adicionado a sua roupa!'
    - ' &7Chique... E confortável.'
    - ''
  cooldown: '&cAguarde {cooldown} segundos antes de pegar outra roupa!'

Progress:
  display-amount: 10
  symbol: '❙'
  complete-color: '&a'
  incomplete-color: '&8'

Experience-Formula: # base + (base * level ^ exponent)
  player-level:
    base-exp: 2500
    exponent: 2.25
  clothes-level:
    base-exp: 350
    exponent: 1.65

Titles:
  rank-up:
    title: '&6&lUP!'
    subtitle: '&7Você evoluiu de nível!'

Sounds:
  rank-up:
    enabled: true
    sound: LEVEL_UP
    volume: 10
    pitch: 4
  armor-up:
    enabled: true
    sound: NOTE_STICKS
    volume: 10
    pitch: 2

Exp-Percentage-Item:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQzNzhiOTg2ZTM1ODU1NWVlNzNmMDliMjEwZDQ5ZWMxMzcxOWRlNWVhODhkNzU1MjM3NzBkMzExNjNmM2FlZiJ9fX0=
  name: '&aFacilitador &7[&f{percentage}%&7]'
  lore:
    - '&7Esse frasco contém uma porcentagem'
    - '&7do EXP restante para você'
    - '&7evoluir de nível!'

Number-Formatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"